title: Tactile Roboticist
description: Saekwang Nam
theme: just-the-docs

# logo: "/assets/images/Saekwang_Nam_magnified.png"
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

url: https://s-nam.github.io

# Aux links for the upper right navigation
aux_links:
  Go to this repository: https://github.com/s-nam/s-nam.github.io

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# External navigation links
nav_external_links:
  - title: Google scholar
    url: https://scholar.google.com/citations?user=DSZzGh0AAAAJ&hl=en


# Color scheme supports "light" (default) and "dark"
color_scheme: light

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code
  # To load mermaid from a local library, also use the `path` key to specify the location of the library; e.g.
  # for (v10+):
  # path: "/assets/js/mermaid.esm.min.mjs"
  # for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js` (<v10) and the associated `.map` file from the specified version of `mermaid/dist` to `/assets/js/`.


# # Define Jekyll collections
# collections:
#   # Define a collection named "tests", its documents reside in the "_tests" directory
#   tests:
#     permalink: "/:collection/:path/"
#     output: true

#   thoughts:
#     output: true
#     # permalink: "/:collection/:path/"
#     categories-order:
#       - life
#       - study

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2017-2023 Saekwang Nam."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# just_the_docs:
#   # Define which collections are used in just-the-docs
#   collections:
#     # Reference the "tests" collection
#     tests:
#       # Give the collection a name
#       name: Tests
#       # Exclude the collection from the navigation
#       # Supports true or false (default)
#       # nav_exclude: true
#       # Fold the collection in the navigation
#       # Supports true or false (default)
#       nav_fold: true  # note: this option is new in v0.4
#       # Exclude the collection from the search
#       # Supports true or false (default)
#       search_exclude: false



# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
ga_tracking: G-6K89WZY232
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
- jekyll-seo-tag
- jekyll-github-metadata

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all